### ISSUE TITLE
reorganize services options in config

### ISSUE THREAD

**Issue by tarekziade** [elastic/connectors-python#1022]
Right now, we have a single `service` section in the `config.yml` file

Let's add one section per service:

```yml
services:
    cleanup:
        option1
    scheduling:
        option2
     dsl:
        etc
```
