### ISSUE TITLE
Add support for environment variables

### ISSUE THREAD

**Issue by tarekziade** [elastic/connectors-python#9]
We want to be able to use `elasticsearch` environment variables in docker, so the config file can look like:

```
elasticsearch:
  host: ${host}
  user: ${username}
  password: {password}
```
